production:
   auto_create: true
   deny_delete: true
   post_create: /opt/alminium/bin/alm-scm-post-create
   allow_add_local: true
   svn:
     path: /var/opt/alminium/svn
     svnadmin: /usr/bin/svnadmin
     url: http(s)://ホスト名/svn
   git:
     path: /var/opt/alminium/git
     git: /usr/bin/git
     options: --bare 
     url: http(s)://ホスト名/git
   mercurial:
     path: /var/opt/alminium/hg
     hg: /usr/bin/hg
     url: http(s)://ホスト名/hg
